# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5e2acaee7f0dc8c0ec16dee29b68078dffc0ce38ed1265b1384e5222ff9ea1cceb6b1c4ae9782b8d26b61d54e0c9dd44f26a156605ff97363c8d596984e8f472
  omniauth_facebook_key: <%= ENV["omniauth_facebook_key"] %>
  omniauth_facebook_secret: <%= ENV["omniauth_facebook_secret"] %>
  omniauth_twitter_key: <%= ENV["omniauth_twitter_key"] %>
  omniauth_twitter_secret: <%= ENV["omniauth_twitter_secret"] %>
  omniauth_google_key: <%= ENV["omniauth_google_key"] %>
  omniauth_google_secret: <%= ENV["omniauth_google_secret"] %>

test:
  secret_key_base: 9bd2add5bed161906a4530d7af6413a7f906f5d3998fdf9eb2ccbceee036ed9ec566ce8d05b6430860eae83ad2d3e90cfda25f69da179a4307ce0694445f6874
  omniauth_facebook_key: <%= ENV["omniauth_facebook_key"] %>
  omniauth_facebook_secret: <%= ENV["omniauth_facebook_secret"] %>
  omniauth_twitter_key: <%= ENV["omniauth_twitter_key"] %>
  omniauth_twitter_secret: <%= ENV["omniauth_twitter_secret"] %>
  omniauth_google_key: <%= ENV["omniauth_google_key"] %>
  omniauth_google_secret: <%= ENV["omniauth_google_secret"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  omniauth_facebook_key: <%= ENV["omniauth_facebook_key"] %>
  omniauth_facebook_secret: <%= ENV["omniauth_facebook_secret"] %>
  omniauth_twitter_key: <%= ENV["omniauth_twitter_key"] %>
  omniauth_twitter_secret: <%= ENV["omniauth_twitter_secret"] %>
  omniauth_google_key: <%= ENV["omniauth_google_key"] %>
  omniauth_google_secret: <%= ENV["omniauth_google_secret"] %>