# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
AdminUser.create!(email: ENV['WEBSHOP_DATABASE_ADMIN_USER'], password: ENV['WEBSHOP_DATABASE_ADMIN_PASSWORD'], password_confirmation: ENV['WEBSHOP_DATABASE_ADMIN_PASSWORD'])
AdminUser.create!(email: 'kisistvan@gmail.com', password: 'kisistvan', password_confirmation: 'kisistvan')
AdminUser.create!(email: 'nagybela@gmail.com', password: 'nagybela', password_confirmation: 'nagybela')
AdminUser.create!(email: 'vargazsolt@gmail.com', password: 'vargazsolt', password_confirmation: 'vargazsolt')
AdminUser.create!(email: 'kissroland@gmail.com', password: 'kissroland', password_confirmation: 'kissroland')
AdminUser.create!(email: 'molnarpeter@gmail.com', password: 'molnarpeter', password_confirmation: 'molnarpeter')

Category.create!(id: 1, name: 'Motherboard')
Category.create!(id: 12, name: 'LGA-1150', parent_id: '1')
Category.create!(id: 13, name: 'LGA-1151', parent_id: '1')
Category.create!(id: 14, name: 'LGA-1155', parent_id: '1')
Category.create!(id: 15, name: 'LGA-2011-3', parent_id: '1')
Category.create!(id: 16, name: 'SOCKET-AM1', parent_id: '1')
Category.create!(id: 17, name: 'SOCKET-AM3', parent_id: '1')
Category.create!(id: 18, name: 'SOCKET-FM2', parent_id: '1')
Category.create!(id: 2, name: 'Processor')
Category.create!(id: 19, name: 'AMD', parent_id: '2')
Category.create!(id: 20, name: 'INTEL', parent_id: '2')
Category.create!(id: 3, name: 'Hard Disk')
Category.create!(id: 21, name: 'Internal HDD', parent_id: '3')
Category.create!(id: 22, name: 'External HDD', parent_id: '3')
Category.create!(id: 4, name: 'SSD')
Category.create!(id: 23, name: 'Internal SSD', parent_id: '4')
Category.create!(id: 24, name: 'External SSD', parent_id: '4')
Category.create!(id: 5, name: 'RAM')
Category.create!(id: 25, name: 'DDR', parent_id: '5')
Category.create!(id: 26, name: 'DDR2', parent_id: '5')
Category.create!(id: 27, name: 'DDR3', parent_id: '5')
Category.create!(id: 28, name: 'DDR4', parent_id: '5')
Category.create!(id: 29, name: 'Notebook', parent_id: '5')
Category.create!(id: 6, name: 'Video Card')
Category.create!(id: 30, name: 'AMD VGA', parent_id: '6')
Category.create!(id: 31, name: 'Nvidia VGA', parent_id: '6')
Category.create!(id: 7, name: 'Keyboard')
Category.create!(id: 32, name: 'Wired Keyboard', parent_id: '7')
Category.create!(id: 33, name: 'Wireless Keyboard', parent_id: '7')
Category.create!(id: 8, name: 'Mouse')
Category.create!(id: 34, name: 'Wired Mouse', parent_id: '8')
Category.create!(id: 35, name: 'Wireless Mouse', parent_id: '8')
Category.create!(id: 9, name: 'Speaker')

Courier.create!(email: 'marinorambert@gmail.com', name: 'Marino Rambert')
Courier.create!(email: 'rocgideon@gmail.com', name: 'Roc Gideon')
Courier.create!(email: 'oscarbranislav@gmail.com', name: 'Oscar Branislav')
Courier.create!(email: 'jedjockie@gmail.com', name: 'Jed Jockie')
Courier.create!(email: 'artemdino@gmail.com', name: 'Artem Dino')

Vendor.create!(id: 1, email: 'intel@usa.com', name: 'INTEL')
Vendor.create!(id: 2, email: 'amd@usa.com', name: 'AMD')
Vendor.create!(id: 3, email: 'asus@usa.com', name: 'ASUS')
Vendor.create!(id: 4, email: 'as_rock@usa.com', name: 'ASROCK')
Vendor.create!(id: 5, email: 'a_data@europe.com', name: 'ADATA')
Vendor.create!(id: 6, email: 'sea_gate@asia.com', name: 'SEAGATE')
Vendor.create!(id: 7, email: 'WD@usa.com', name: 'WESTERN DIGITAL')
Vendor.create!(id: 8, email: 'kingston@asia.com', name: 'KINGSTON')
Vendor.create!(id: 9, email: 'hyperX@usa.com', name: 'HyperX')
Vendor.create!(id: 10, email: 'nvidia@usa.com', name: 'NVIDIA')
Vendor.create!(id: 11, email: 'genius@usa.com', name: 'GENIUS')
Vendor.create!(id: 12, email: 'microsoft@usa.com', name: 'MICROSOFT')
Vendor.create!(id: 13, email: '4world@asia.com', name: '4WORLD')
Vendor.create!(id: 14, email: 'gembird@asia.com', name: 'GEMBIRD')
Vendor.create!(id: 15, email: 'razer@usa.com', name: 'RAZER')
Vendor.create!(id: 16, email: 'gigabyte@usa.com', name: 'GIGABYTE')
Vendor.create!(id: 17, email: 'epson@usa.com', name: 'EPSON')
Vendor.create!(id: 18, email: 'canon@usa.com', name: 'CANON')
Vendor.create!(id: 19, email: 'samsung@asia.com', name: 'SAMSUNG')
Vendor.create!(id: 20, email: 'hp@usa.com', name: 'HP')

Product.create!(image_url: Settings::ROOT + 'products/10000.jpg', category_id: 12, price: '12446', discount: '0', name: 'ASUS H81M-R', stock: '5', description: 'ASUS H81M-R típusú alaplap LGA-1150 foglalattal, Intel H81 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: Gigabit. 8db USB port.', wholesale_price: '7467', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10001.jpg', category_id: 12, price: '27523', discount: '0', name: 'ASUS B85-PLUS', stock: '6', description: 'ASUS B85-PLUS típusú alaplap LGA-1150 foglalattal, Intel B85 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 12db USB port.', wholesale_price: '19266', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10002.jpg', category_id: 12, price: '40490', discount: '0', name: 'ASUS Z97-AR', stock: '3', description: 'ASUS Z97-AR típusú alaplap LGA-1150 foglalattal, Intel Z97 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 14db USB port.', wholesale_price: '28343', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10003.jpg', category_id: 12, price: '93873', discount: '0', name: 'ASUS Z87-WS', stock: '2', description: 'ASUS Z87-WS típusú alaplap LGA-1150 foglalattal, Intel Z87 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 15db USB és FireWire port.', wholesale_price: '65711', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10004.jpg', category_id: 12, price: '19172', discount: '0', name: 'ASROCK B85 Anniversary', stock: '4', description: 'ASROCK B85 Anniversary típusú alaplap LGA-1150 foglalattal, Intel B85 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 12db USB port.', wholesale_price: '13420', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10005.jpg', category_id: 12, price: '26825', discount: '0', name: 'ASROCK H81TM-ITX', stock: '4', description: 'ASROCK H81TM-ITX típusú alaplap LGA-1150 foglalattal, Intel H81 chipsettel, Processzorban integrált videókártyával, 2db Notebook DDR3 (SO-DIMM) memóriafoglalattal (max 16GB). LAN: 10/100/1000MBps /Gigabit/. 8db USB port.', wholesale_price: '18777', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10006.jpg', category_id: 12, price: '77617', discount: '0', name: 'ASROCK Z97 OC Formula', stock: '3', description: 'ASROCK Z97 OC Formula típusú alaplap LGA-1150 foglalattal, Intel Z97 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 14db USB port.', wholesale_price: '54331', vendor_id: '4')

Product.create!(image_url: Settings::ROOT + 'products/10007.jpg', category_id: 13, price: '16601', discount: '0', name: 'ASUS H110M-D D3', stock: '12', description: 'ASUS H110M-D D3 típusú alaplap LGA-1151 foglalattal, Intel H110 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 32GB). 10db USB port.', wholesale_price: '11620', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10008.jpg', category_id: 13, price: '28207', discount: '0', name: 'ASUS B150M-PLUS', stock: '7', description: 'ASUS B150M-PLUS típusú alaplap LGA-1151 foglalattal, Intel B150 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). 11db USB port.', wholesale_price: '19744', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10009.jpg', category_id: 13, price: '32791', discount: '0', name: 'ASUS Z170-P', stock: '6', description: 'ASUS Z170-P típusú alaplap LGA-1151 foglalattal, Intel Z170 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). LAN: Gigabit. 6 darab USB 2.0 és 6 darab USB 3.0 port.', wholesale_price: '22953', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10010.jpg', category_id: 13, price: '90068', discount: '0', name: 'ASUS Z170-DELUXE', stock: '3', description: 'ASUS Z170-DELUXE típusú alaplap LGA-1151 foglalattal, Intel Z170 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). LAN: Gigabit. 5 darab USB 2.0, 5 darab USB 3.0 és 6 darab USB 3.1 port.', wholesale_price: '63047', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10011.jpg', category_id: 13, price: '131737', discount: '0', name: 'ASUS MAXIMUS VIII EXTREME', stock: '2', description: 'ASUS MAXIMUS VIII EXTREME típusú alaplap LGA-1151 foglalattal, Intel Z170 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). 18db USB port.', wholesale_price: '92215', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10012.jpg', category_id: 13, price: '16497', discount: '0', name: 'ASROCK H110M-DVS/D3', stock: '9', description: 'ASROCK H110M-DVS/D3 típusú alaplap LGA-1151 foglalattal, Intel H110 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 32GB). 10db USB port.', wholesale_price: '11548', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10013.jpg', category_id: 13, price: '29700', discount: '0', name: 'ASROCK H170M Pro4', stock: '6', description: 'ASROCK H170M Pro4 típusú alaplap LGA-1151 foglalattal, Intel H170 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). LAN: Gigabit. 10db USB port.', wholesale_price: '20790', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10014.jpg', category_id: 13, price: '76631', discount: '0', name: 'ASROCK Z170 Extreme7+', stock: '2', description: 'ASROCK Z170 Extreme7+ típusú alaplap LGA-1151 foglalattal, Intel Z170 chipsettel, Processzorban integrált videókártyával, 4db DDR4 memóriafoglalattal (max 64GB). LAN: Gigabit. 18db USB port.', wholesale_price: '53641', vendor_id: '4')

Product.create!(image_url: Settings::ROOT + 'products/10015.jpg', category_id: 14, price: '18086', discount: '0', name: 'ASUS H61M-K', stock: '5', description: 'ASUS H61M-K típusú alaplap LGA-1155 foglalattal, Intel H61 chipsettel, Intel HD Graphics (2/3/4/5000) integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: 10/100/1000MBps /Gigabit/. 8db USB port.', wholesale_price: '12660', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10016.jpg', category_id: 14, price: '13881', discount: '0', name: 'ASROCK H61M-VG4', stock: '6', description: 'ASROCK H61M-VG4 típusú alaplap LGA-1155 foglalattal, Intel H61 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: 10/100/1000MBps /Gigabit/. 8db USB port.', wholesale_price: '9716', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10017.jpg', category_id: 14, price: '16699', discount: '0', name: 'ASROCK H61M-DGS', stock: '3', description: 'ASROCK H61M-DGS típusú alaplap LGA-1155 foglalattal, Intel H61 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: 10/100/1000MBps Gigabit/. 10db USB port.', wholesale_price: '11689', vendor_id: '4')

Product.create!(image_url: Settings::ROOT + 'products/10018.jpg', category_id: 15, price: '82791', discount: '0', name: 'ASUS X99-A', stock: '3', description: 'ASUS X99-A típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 8db DDR4 memóriafoglalattal (max 64GB). LAN: 10/100/1000MBps /Gigabit/. 18db USB port.', wholesale_price: '57953', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10019.jpg', category_id: 15, price: '133902', discount: '0', name: 'ASUS RAMPAGE V EXTREME/U3.1', stock: '3', description: 'ASUS RAMPAGE V EXTREME/U3.1 típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 8db DDR4 memóriafoglalattal (max 64GB). LAN: Gigabit. 22db USB port.', wholesale_price: '93731', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10020.jpg', category_id: 15, price: '64187', discount: '0', name: 'ASROCK X99 Extreme3', stock: '8', description: 'ASROCK X99 Extreme3 típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 4db DDR4 memóriafoglalattal (max 64GB). LAN: 10/100/1000MBps /Gigabit/. 14db USB port.', wholesale_price: '44930', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10021.jpg', category_id: 15, price: '225741', discount: '0', name: 'ASROCK X99 Extreme11', stock: '4', description: 'ASROCK X99 Extreme11 típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 8db DDR4 memóriafoglalattal (max 128GB). LAN: 10/100/1000MBps /Gigabit/. 16db USB port.',wholesale_price: '158018', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10022.jpg', category_id: 15, price: '66364', discount: '0', name: 'GIGABYTE GA-X99-UD3', stock: '7', description: 'GIGABYTE GA-X99-UD3 típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 4db DDR4 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 16db USB port.',wholesale_price: '46454', vendor_id: '16')
Product.create!(image_url: Settings::ROOT + 'products/10023.jpg', category_id: 15, price: '89271', discount: '0', name: 'GIGABYTE GA-X99-UD4P', stock: '2', description: 'GIGABYTE GA-X99-UD4P típusú alaplap LGA-2011-3 foglalattal, Intel X99 chipsettel, 8db DDR4 memóriafoglalattal (max 128GB). LAN: Gigabit. 16db USB port.', wholesale_price: '62489', vendor_id: '16')

Product.create!(image_url: Settings::ROOT + 'products/10024.jpg', category_id: 16, price: '9652', discount: '0', name: 'ASUS AM1M-A', stock: '4', description: 'ASUS AM1M-A típusú alaplap Socket-AM1 foglalattal, AMD Processzorba integrált chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 32GB). LAN:10/100/1000MBps /Gigabit/. 8db USB port.',wholesale_price: '6756', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10025.jpg', category_id: 16, price: '9257', discount: '0', name: 'ASROCK AM1B-M', stock: '3', description: 'ASROCK AM1B-M típusú alaplap Socket-AM1 foglalattal, AMD Processzorba integrált chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: 10/100/1000MBps /Gigabit/. 8db USB port.',wholesale_price: '6480', vendor_id: '4')

Product.create!(image_url: Settings::ROOT + 'products/10026.jpg', category_id: 17, price: '15431', discount: '0', name: 'ASUS M5A78L-M LE/USB3', stock: '3', description: 'ASUS M5A78L-M LE/USB3 típusú alaplap Socket-AM3 foglalattal, AMD 760G chipsettel, AMD RadeOn HD3200 integrált videókártyával, 2db DDR3 memóriafoglalattal (max 16GB). LAN: Gigabit. 10db USB port.',wholesale_price: '10801', vendor_id: '3')

Product.create!(image_url: Settings::ROOT + 'products/10027.jpg', category_id: 18, price: '18098', discount: '0', name: 'ASUS A68HM-K', stock: '11', description: 'ASUS A68HM-K típusú alaplap Socket-FM2+ foglalattal, AMD A68 chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 32GB). LAN: 10/100/1000MBps /Gigabit/. 8db USB port.',wholesale_price: '12668', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10028.jpg', category_id: 18, price: '49025', discount: '0', name: 'ASUS CROSSBLADE RANGER', stock: '5', description: 'ASUS CROSSBLADE RANGER típusú alaplap Socket-FM2+ foglalattal, AMD A88X chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 64GB). LAN: 10/100/1000MBps /Gigabit/. 14db USB port.',wholesale_price: '34318', vendor_id: '3')
Product.create!(image_url: Settings::ROOT + 'products/10029.jpg', category_id: 18, price: '22005', discount: '0', name: 'ASROCK FM2A78M Pro4+', stock: '7', description: 'ASROCK FM2A78M Pro4+ típusú alaplap Socket-FM2+ foglalattal, AMD A78 chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 64GB). LAN: 10/100/1000MBps /Gigabit/. 14db USB port.',wholesale_price: '15404', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10030.jpg', category_id: 18, price: '29219', discount: '0', name: 'ASROCK A88M-ITX/ac', stock: '3', description: 'ASROCK A88M-ITX/ac típusú alaplap Socket-FM2+ foglalattal, AMD A88X chipsettel, Processzorban integrált videókártyával, 2db DDR3 memóriafoglalattal (max 32GB). 12db USB port.',wholesale_price: '20453', vendor_id: '4')
Product.create!(image_url: Settings::ROOT + 'products/10031.jpg', category_id: 18, price: '24790', discount: '0', name: 'GIGABYTE GA-F2A88X-D3H', stock: '6', description: 'GIGABYTE GA-F2A88X-D3H típusú alaplap Socket-FM2+ foglalattal, AMD A88X chipsettel, Processzorban integrált videókártyával, 4db DDR3 memóriafoglalattal (max 64GB). LAN: 10/100/1000MBps /Gigabit/. 12db USB port.',wholesale_price: '17353', vendor_id: '16')

Product.create!(image_url: Settings::ROOT + 'products/10032.jpg', category_id: 19, price: '6922', discount: '0', name: 'AMD A4-3300 2.50GHz FM1 BOX', stock: '5', description: 'Foglalat: Socket-FM1 Cache: 1 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 32 nm Órajel : 2500 MHz',wholesale_price: '4845', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10033.jpg', category_id: 19, price: '9195', discount: '0', name: 'AMD A4-4000 3.00GHz FM2 BOX', stock: '6', description: 'Foglalat: Socket-FM2 Cache: 1 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 32 nm Órajel : 3000 MHz',wholesale_price: '6437', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10034.jpg', category_id: 19, price: '15469', discount: '0', name: 'AMD A6-6420K 4.00GHz FM2 BOX', stock: '4', description: 'Foglalat: Socket-FM2 Cache: 1 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 32 nm Órajel : 4000 MHz',wholesale_price: '10828', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10035.jpg', category_id: 19, price: '22222', discount: '0', name: 'AMD A8-7600 3.10GHz FM2+ BOX', stock: '2', description: 'Foglalat: Socket-FM2+ Cache: 4 MB Magok száma: 4 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 28 nm Órajel : 3100 MHz',wholesale_price: '15555', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10036.jpg', category_id: 19, price: '28405', discount: '0', name: 'AMD A10-7700K 3.50GHz FM2+ BOX', stock: '6', description: 'Foglalat: Socket-FM2+ Cache: 4 MB Magok száma: 4 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 28 nm Órajel : 3400 MHz',wholesale_price: '19883', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10037.jpg', category_id: 19, price: '37087', discount: '0', name: 'AMD FX-8300 3.30GHz AM3+ BOX', stock: '8', description: 'Foglalat: Socket-AM3+ Cache: 8 MB Magok száma: 8 db Dobozos: Igen Integrált VGA: Nem Gyártási technológia : 32 nm Órajel : 3300 MHz',wholesale_price: '25961', vendor_id: '2')
Product.create!(image_url: Settings::ROOT + 'products/10038.jpg', category_id: 19, price: '57398', discount: '0', name: 'AMD FX-8370 4.00GHz AM3+ BOX', stock: '3', description: 'Foglalat: Socket-AM3+ Cache: 8 MB Magok száma: 8 db Dobozos: Igen Integrált VGA: Nem Gyártási technológia : 32 nm Órajel : 4000 MHz',wholesale_price: '40179', vendor_id: '2')

Product.create!(image_url: Settings::ROOT + 'products/10039.jpg', category_id: 20, price: '11052', discount: '0', name: 'INTEL Celeron G1820 2.70GHz 1150 BOX', stock:'3', description: 'Foglalat: LGA-1150 Cache: 2 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 2700 MHz',wholesale_price: '7736', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10040.jpg', category_id: 20, price: '16441', discount: '0', name: 'INTEL Pentium G3240 3.10GHz 1150 BOX', stock:'5', description: 'Foglalat: LGA-1150 Cache: 3 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 3100 MHz',wholesale_price: '11508', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10041.jpg', category_id: 20, price: '21057', discount: '0', name: 'INTEL Pentium G3258 3.20GHz 1150 BOX', stock:'6', description: 'Foglalat: LGA-1150 Cache: 3 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 3200 MHz',wholesale_price: '14740', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10042.jpg', category_id: 20, price: '33175', discount: '0', name: 'INTEL Core i3-4150 3.50GHz 1150 BOX', stock:'4', description: 'Foglalat: LGA-1150 Cache: 3 MB Magok száma: 2 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 3500 MHz',wholesale_price: '23223', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10043.jpg', category_id: 20, price: '52060', discount: '0', name: 'INTEL Core i5-4440 3.10GHz 1150 BOX', stock:'7', description: 'Foglalat: LGA-1150 Cache: 6 MB Magok száma: 4 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 3100 MHz',wholesale_price: '36442', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10044.jpg', category_id: 20, price: '66876', discount: '0', name: 'INTEL Core i5-4430 3.00GHz 1150 OEM', stock:'3', description: 'Foglalat: LGA-1150 Cache: 6 MB Magok száma: 4 db Dobozos: Nem Integrált VGA: Igen Gyártási technológia : 22 nm Órajel : 3000 MHz',wholesale_price: '46813', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10045.jpg', category_id: 20, price: '80755', discount: '0', name: 'INTEL Core i5-6600 3.30GHz 1151 OEM', stock:'5', description: 'Foglalat: LGA-1151 Cache: 6 MB Magok száma: 4 db Dobozos: Nem Integrált VGA: Igen Gyártási technológia : 14 nm Órajel : 3300 MHz',wholesale_price: '56529', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10046.jpg', category_id: 20, price: '107064', discount: '0', name: 'INTEL Core i7-6700K 4.00GHz 1151 BOX', stock:'2', description: 'Foglalat: LGA-1151 Cache: 8 MB Magok száma: 4 db Dobozos: Igen Integrált VGA: Igen Gyártási technológia : 14 nm Órajel : 4000 MHz',wholesale_price: '74945', vendor_id: '1')
Product.create!(image_url: Settings::ROOT + 'products/10047.jpg', category_id: 20, price: '377871', discount: '0', name: 'INTEL Core i7-5960X 3.00GHz 2011-3 Extreme Edition OEM', stock:'1', description: 'Foglalat: LGA-2011-3 Cache: 20 MB Magok száma: 8 db Dobozos: Nem Integrált VGA: Nem Gyártási technológia : 22 nm Órajel : 3000 MHz',wholesale_price: '264510',vendor_id: '1')

Product.create!(image_url: Settings::ROOT + 'products/10048.jpg', category_id: 21, price: '14580', discount: '0', name: 'SEAGATE Barracuda 500GB 7200rpm 16MB SATA3 ST500DM002X', stock:'11', description: 'Fantázianév : Barracuda Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 500GB Fordulat: 7200 rpm Puffer: 16 MB Méret: 3,5"',wholesale_price: '10206',vendor_id: '6')
Product.create!(image_url: Settings::ROOT + 'products/10049.jpg', category_id: 21, price: '14992', discount: '0', name: 'SEAGATE Barracuda 1TB 7200rpm 64MB SATA3 ST1000DM003', stock:'5', description: 'Fantázianév : Barracuda Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 1TB Fordulat: 7200 rpm Puffer: 64 MB Méret: 3,5"',wholesale_price: '10494',vendor_id: '6')
Product.create!(image_url: Settings::ROOT + 'products/10050.jpg', category_id: 21, price: '18703', discount: '0', name: 'SEAGATE Pipeline HD 500GB 5900rpm 8MB SATA2 ST3500312CS', stock:'3', description: 'Fantázianév : Pipeline HD Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 500GB Fordulat: 5900 rpm Puffer: 8 MB Méret: 3,5"',wholesale_price: '13092',vendor_id: '6')
Product.create!(image_url: Settings::ROOT + 'products/10051.jpg', category_id: 21, price: '26187', discount: '0', name: 'SEAGATE NAS 2TB 5900rpm 64MB SATA3 ST2000VN000', stock:'4', description: 'Fantázianév : NAS Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 2TB Fordulat: 5900 rpm Puffer: 64 MB Méret: 3,5"',wholesale_price: '18330',vendor_id: '6')
Product.create!(image_url: Settings::ROOT + 'products/10052.jpg', category_id: 21, price: '20585', discount: '0', name: 'SAMSUNG SpinPoint D8X 1TB 7200 rpm 32 MB SATA3 ST1000LM044', stock:'4', description: 'Fantázianév : SpinPoint D8X Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 1TB Fordulat: 7200 rpm Puffer: 32 MB Méret: 2,5" Magasság: 9.5 mm',wholesale_price: '14410',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10053.jpg', category_id: 21, price: '11303', discount: '0', name: 'WD AV 320GB 5400rpm 8MB SATA2 WD3200BVVT', stock:'2', description: 'Fantázianév : AV Típus : Belso Csatlakozás: SATA2 Tároló kapacitás: 320GB Fordulat: 5400 rpm Puffer: 8 MB Méret: 3,5"',wholesale_price: '7912',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10054.jpg', category_id: 21, price: '14873', discount: '0', name: 'WD Blue 500GB 7200rpm 16MB SATA3 WD5000AAKX', stock:'5', description: 'Fantázianév : Blue Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 500GB Fordulat: 7200 rpm Puffer: 16 MB Méret: 3,5"',wholesale_price: '10410',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10055.jpg', category_id: 21, price: '17442', discount: '0', name: 'WD Blue 320GB 5400rpm 16MB SATA3 WD3200LPCX', stock:'10', description: 'Fantázianév : Blue Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 320GB Fordulat: 5400 rpm Puffer: 16 MB Méret: 2,5"',wholesale_price: '12210',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10056.jpg', category_id: 21, price: '26269', discount: '0', name: 'WD AV 2TB 5400 rpm 64 MB SATA3 WD20EURX', stock:'7', description: 'Fantázianév : AV Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 2TB Fordulat: 5400 rpm Puffer: 64 MB Méret: 3,5"',wholesale_price: '18390',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10057.jpg', category_id: 21, price: '33053', discount: '0', name: 'WD Red 3TB 5400rpm 64MB SATA3 WD30EFRX', stock:'20', description: 'Fantázianév : Red Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 3TB Fordulat: 5400 rpm Puffer: 64 MB Méret: 3,5"',wholesale_price: '23137',vendor_id: '7')

Product.create!(image_url: Settings::ROOT + 'products/10058.jpg', category_id: 22, price: '19392', discount: '0', name: 'ADATA DashDrive HV620 500GB 5400rpm 8MB USB 3.0 Fekete AHV620-500GU3-CBK', stock:'3', description: 'Fantázianév : DashDrive HV620 Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 500GB Fordulat: 5400 rpm Puffer: 8 MB  Méret: 2,5" Szín : Fekete',wholesale_price: '13580',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10059.jpg', category_id: 22, price: '20117', discount: '0', name: 'ADATA HV100 500GB 5400rpm 8MB USB 3.0 Fehér AHV100-500GU3-CWH', stock:'14', description: 'Fantázianév : HV100 Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 500GB Fordulat: 5400 rpm Puffer: 8 MB Méret: 2,5" Szín : Fehér',wholesale_price: '14082',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10060.jpg', category_id: 22, price: '23176', discount: '0', name: 'ADATA Durable HD710 1TB 5400rpm 8MB USB 3.0 Kék AHD710-1TU3-CBL', stock:'3', description: 'Fantázianév : Durable HD710 Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 1TB Fordulat: 5400 rpm Puffer: 8 MB Méret: 2,5" Szín : Kék',wholesale_price: '16223',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10061.jpg', category_id: 22, price: '48925', discount: '0', name: 'SAMSUNG D3 Station 5TB 5400rpm 32MB USB 3.0 Fekete STSHX-D501TDB', stock:'4', description: 'Fantázianév : D3 Station Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 5TB Fordulat: 5400 rpm Puffer: 32 MB Méret: 3,5"Szín : Fekete',wholesale_price: '34250',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10062.jpg', category_id: 22, price: '73285', discount: '0', name: 'SAMSUNG D3 Station 6TB 5400rpm 32MB USB 3.0 Fekete STSHX-D601TDB', stock:'3', description: 'Fantázianév : D3 Station Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 6TB Fordulat: 5400 rpm Puffer: 32 MB Méret: 3,5" Szín : Fekete',wholesale_price: '51300',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10063.jpg', category_id: 22, price: '21222', discount: '0', name: 'WD Elements Portable 1TB 5400rpm 8MB USB 3.0 Fekete WDBUZG0010BBK', stock:'3', description: 'Fantázianév : Elements Portable Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 1TB Fordulat: 5400 rpm Puffer: 8 MB Méret: 2,5" Szín : Fekete',wholesale_price: '14855',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10064.jpg', category_id: 22, price: '25538', discount: '0', name: 'WD My Passport Ultra Metal 1TB 5400rpm 32MB USB 3.0 Ezüst WDBTYH0010BSL', stock:'3', description: 'Fantázianév : My Passport Ultra Metal Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 1TB Fordulat: 5400 rpm Puffer: 32 MB Méret: 2,5" Szín : Ezüst',wholesale_price: '17880',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10065.jpg', category_id: 22, price: '33189', discount: '0', name: 'WD My Passport Ultra 2TB 5400 rpm 32MB USB 3.0 Fekete WDBBKD0020BBK', stock:'6', description: 'Fantázianév : My Passport Ultra Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 2TB Fordulat: 5400 rpm Puffer: 32 MB Méret: 2,5" Szín : Fekete',wholesale_price: '23230',vendor_id: '7')
Product.create!(image_url: Settings::ROOT + 'products/10066.jpg', category_id: 22, price: '97208', discount: '0', name: 'WD My Book 8TB 5700rpm 32MB USB 3.0 Fekete WDBFJK0080HBK', stock:'2', description: 'Fantázianév : My Book Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 8TB Fordulat: 5700 rpm Puffer: 32 MB Méret: 3,5" Szín : Fekete',wholesale_price: '68000',vendor_id: '7')

Product.create!(image_url: Settings::ROOT + 'products/10067.jpg', category_id: 23, price: '12982', discount: '0', name: 'KINGSTON 120GB SSDNow V300 SATA3 2,5" SV300S37A/120G', stock:'11', description: 'Fantázianév : SSDNow V300 Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 120GB Méret: 2,5" Technológia : MLC SSD max írás: 133 MB/s SSD max olvasás: 180 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '9100',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10068.jpg', category_id: 23, price: '26810', discount: '0', name: 'KINGSTON 240GB SSDNow V300 SATA3 2,5" SV300S3B7A/240G', stock:'10', description: 'Fantázianév : SSDNow V300 Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 240GB Méret: 2,5" Technológia : MLC SSD max írás: 142 MB/s SSD max olvasás: 191 MB/s Magasság: 7 mm Kiszerelés : Desktop (Meghajtó + beépíto keret)',wholesale_price: '18767',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10069.jpg', category_id: 23, price: '47325', discount: '0', name: 'KINGSTON 480GB SSDNow V300 SATA3 2,5" SV300S3B7A/480G', stock:'11', description: 'Fantázianév : SSDNow V300 Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 480GB Méret: 2,5" Technológia : MLC SSD max írás: 208 MB/s SSD max olvasás: 450 MB/s Magasság: 7 mm Kiszerelés : Desktop (Meghajtó + beépíto keret)',wholesale_price: '33128',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10070.jpg', category_id: 23, price: '21652', discount: '0', name: 'SAMSUNG 120GB 850 EVO SATA3 2,5" MZ-75E120B', stock:'9', description: 'Fantázianév : 850 EVO Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 120GB méret: 2,5" Technológia : TLC SSD max írás: 520 MB/s SSD max olvasás: 550 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '15156',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10071.jpg', category_id: 23, price: '24759', discount: '0', name: 'SAMSUNG 120GB 850 EVO SATA3 2,5" MZ-75E120B', stock:'2', description: 'Fantázianév : 850 EVO Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 120GB Méret: 2,5" Technológia : TLC SSD max írás: 520 MB/s SSD max olvasás: 550 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '17331',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10072.jpg', category_id: 23, price: '30692', discount: '0', name: 'SAMSUNG 128GB 850 PRO SATA3 2,5" MZ-7KE128BW', stock:'11', description: 'Fantázianév : 850 PRO Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 128GB Méret: 2,5" Technológia : MLC SSD max írás: 470 MB/s SSD max olvasás: 550 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '21500',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10073.jpg', category_id: 23, price: '44006', discount: '0', name: 'SAMSUNG 256GB 850 PRO SATA3 2,5" MZ-7KE256BW', stock:'11', description: 'Fantázianév : 850 PRO Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 256GB Méret: 2,5" Technológia : MLC SSD max írás: 520 MB/s SSD max olvasás: 550 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '30800',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10074.jpg', category_id: 23, price: '66223', discount: '0', name: 'SAMSUNG 512GB 850 PRO SATA3 2,5" MZ-7KE512BW', stock:'11', description: 'Fantázianév : 850 PRO Típus : Belso Csatlakozás: SATA3 Tároló kapacitás: 512GB Méret: 2,5" Technológia : MLC SSD max írás: 520 MB/s SSD max olvasás: 550 MB/s Magasság: 7 mm Kiszerelés : Bundle (Csak a meghajtó)',wholesale_price: '46356',vendor_id: '19')

Product.create!(image_url: Settings::ROOT + 'products/10075.jpg', category_id: 24, price: '35067', discount: '0', name: 'SAMSUNG 250GB T1 USB 3.0 2,5" MU-PS250B/EU', stock:'5', description: 'Fantázianév : T1 Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 250GB Méret: 2,5" Technológia : MLC SSD max írás: 400 MB/s SSD max olvasás: 450 MB/s Kiszerelés : Notebook (Meghajtó + USB kábel)',wholesale_price: '24546',vendor_id: '19')
Product.create!(image_url: Settings::ROOT + 'products/10076.jpg', category_id: 24, price: '42045', discount: '0', name: 'SAMSUNG 250GB T1 USB 3.0 2,5" MU-PS250B/EU', stock:'11', description: 'Fantázianév : T1 Típus : Külso Csatlakozás: USB 3.0 Tároló kapacitás: 250GB Méret: 2,5" Technológia : MLC SSD max írás: 400 MB/s SSD max olvasás: 450 MB/s Kiszerelés : Notebook (Meghajtó + USB kábel)',wholesale_price: '29431',vendor_id: '19')

Product.create!(image_url: Settings::ROOT + 'products/10077.jpg', category_id: 25, price: '4737', discount: '0', name: 'ADATA 512MB DDR 400MHz CL3 AD1U400A512M3-B', stock:'2', description: 'Memória mérete: 512MB Memória típusa: DDR Frekvencia : 400 MHz Késleltetés : CL3',wholesale_price: '3316',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10078.jpg', category_id: 25, price: '5719', discount: '0', name: 'ADATA 512MB DDR 400MHz CL3 AD1U400A512M3-R/S', stock:'3', description: 'Memória mérete: 512MB Memória típusa: DDR Frekvencia : 400 MHz Késleltetés : CL3',wholesale_price: '4003',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10079.jpg', category_id: 25, price: '8573', discount: '0', name: 'ADATA 1GB DDR 400MHz AD1U400A1G3-B', stock:'3', description: 'Memória mérete: 1GB Memória típusa: DDR Frekvencia : 400 MHz',wholesale_price: '6001',vendor_id: '5')

Product.create!(image_url: Settings::ROOT + 'products/10080.jpg', category_id: 26, price: '5220', discount: '0', name: 'ADATA 1GB Premier DDR2 800MHz CL5 AD2U800B1G5-B', stock:'4', description: 'Memória mérete: 1GB Memória típusa: DDR2 Frekvencia : 800 MHz Késleltetés : CL5',wholesale_price: '3654',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10081.jpg', category_id: 26, price: '9246', discount: '0', name: 'ADATA 2GB DDR2 800MHz CL5 AD2U800B2G5-R', stock:'5', description: 'Memória mérete: 2GB Memória típusa: DDR2 Frekvencia : 800 MHz Késleltetés : CL5',wholesale_price: '6472',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10082.jpg', category_id: 26, price: '12216', discount: '0', name: 'ADATA 2GB Premier DDR2 800MHz CL6 AD2U800B2G6-S', stock:'3', description: 'Memória mérete: 2GB Memória típusa: DDR2 Frekvencia : 800 MHz Késleltetés : CL6',wholesale_price: '8551',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10083.jpg', category_id: 26, price: '5410', discount: '0', name: 'KINGSTON 1GB DDR2 667MHz KTD-DM8400B/1G', stock:'5', description: 'Memória mérete: 1GB Memória típusa: DDR2 Frekvencia : 667 MHz',wholesale_price: '3787',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10084.jpg', category_id: 26, price: '9639', discount: '0', name: 'KINGSTON 2GB DDR2 667MHz D25664F50', stock:'4', description: 'Memória mérete: 2GB Memória típusa: DDR2 Frekvencia : 667 MHz',wholesale_price: '6747',vendor_id: '8')

Product.create!(image_url: Settings::ROOT + 'products/10085.jpg', category_id: 27, price: '6579', discount: '0', name: 'ADATA 4GB DDR3 1333MHz CL9 AD3U1333W4G9-R', stock:'6', description: 'Memória mérete: 4GB Memória típusa: DDR3 Frekvencia : 1333 MHz Késleltetés : CL9',wholesale_price: '4605',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10086.jpg', category_id: 27, price: '12592', discount: '0', name: 'ADATA 8GB DDR3 1600MHz CL11 AD3U1600W8G11-R', stock:'8', description: 'Memória mérete: 8GB Memória típusa: DDR3 Frekvencia : 1600 MHz Késleltetés : CL11',wholesale_price: '8815',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10087.jpg', category_id: 27, price: '15245', discount: '0', name: 'ADATA 8GB XPG V2.0 DDR3 1600MHz CL9 KIT AX3U1600W4G9-DMV', stock:'3', description: 'Memória mérete: 8GB Memória típusa: DDR3 Frekvencia : 1600 MHz Késleltetés : CL9 KIT kiszerelés : 2 db',wholesale_price: '10672',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10088.jpg', category_id: 27, price: '32465', discount: '0', name: 'ADATA 16GB XPG V2 DDR3 2400MHz CL11 KIT AX3U2400W8G11-DGV', stock:'2', description: 'Memória mérete: 16GB Memória típusa: DDR3 Frekvencia : 2400 MHz Késleltetés : CL11 KIT kiszerelés : 2 db',wholesale_price: '22726',vendor_id: '5')
Product.create!(image_url: Settings::ROOT + 'products/10089.jpg', category_id: 27, price: '4149', discount: '0', name: 'KINGSTON 2GB DDR3 1333MHz CL9 KVR13N9S6/2', stock:'5', description: 'Memória mérete: 2GB Memória típusa: DDR3 Frekvencia : 1333 MHz Késleltetés : CL9',wholesale_price: '2904',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10090.jpg', category_id: 27, price: '6205', discount: '0', name: 'KINGSTON 4GB DDR3 1600MHz CL11 KVR16N11S8H/4', stock:'11', description: 'Memória mérete: 4GB Memória típusa: DDR3 Frekvencia : 1600 MHz Késleltetés : CL11',wholesale_price: '4344',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10091.jpg', category_id: 27, price: '12175', discount: '0', name: 'KINGSTON 8GB DDR3 1600MHz KTL-TC316L/8G', stock:'8', description: 'Memória mérete: 8GB Memória típusa: DDR3 Frekvencia : 1600 MHz',wholesale_price: '8523',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10092.jpg', category_id: 27, price: '32295', discount: '0', name: 'KINGSTON 16GB DDR3 1333MHz KTH-PL313LV/16G', stock:'5', description: 'Memória mérete: 16GB Memória típusa: DDR3 Frekvencia : 1333 MHz',wholesale_price: '22607',vendor_id: '8')
Product.create!(image_url: Settings::ROOT + 'products/10093.jpg', category_id: 27, price: '6096', discount: '0', name: 'HyperX 4GB FURY DDR3 1600MHz CL10 HX316C10FB/4', stock:'6', description: 'Memória mérete: 4GB Memória típusa: DDR3 Frekvencia : 1600 MHz Késleltetés : CL10',wholesale_price: '4267',vendor_id: '9')
Product.create!(image_url: Settings::ROOT + 'products/10094.jpg', category_id: 27, price: '10789', discount: '0', name: 'HyperX 8GB FURY DDR3 1866MHz CL10 HX318C10F/8', stock:'5', description: 'Memória mérete: 8GB Memória típusa: DDR3 Frekvencia : 1866 MHz Késleltetés : CL10',wholesale_price: '7553',vendor_id: '9')

Product.create!(image_url: Settings::ROOT + 'products/10095.jpg', category_id: 28, price: '11365', discount: '0', name: 'ADATA 4GB XPG Z1 DDR4 3333Mhz CL16 AX4U3333W4G16-BGZ', stock:'7', description:'Memória mérete: 4GB Memória típusa: DDR4 Frekvencia : 3333 MHz Késleltetés : CL16',wholesale_price: '7956',vendor_id: '5');
Product.create!(image_url: Settings::ROOT + 'products/10096.jpg', category_id: 28, price: '6134', discount: '0', name: 'KINGSTON 4GB DDR4 2133MHz KCP421NS8/4', stock:'5', description:'Memória mérete: 4GB Memória típusa: DDR4 Frekvencia : 2133 MHz',wholesale_price:'4294',vendor_id: '8');
Product.create!(image_url: Settings::ROOT + 'products/10097.jpg', category_id: 28, price: '10643', discount: '0', name: 'KINGSTON 8GB DDR4 2133MHz CL15 KVR21N15S8/8', stock:'12', description:'Memória mérete: 8GB Memória típusa: DDR4 Frekvencia : 2133 MHz Késleltetés : CL15',wholesale_price:'7450',vendor_id: '8');
Product.create!(image_url: Settings::ROOT + 'products/10098.jpg', category_id: 28, price: '19841', discount: '0', name: 'KINGSTON 16GB DDR4 2133MHz CL15 KVR21N15D8/16', stock:'3', description:'Memória mérete: 16GB Memória típusa: DDR4 Frekvencia : 2133 MHz Késleltetés : CL15',wholesale_price:'13888',vendor_id: '8');

Product.create!(image_url: Settings::ROOT + 'products/10099.jpg', category_id: 29, price:'6882', discount:'0', name: 'ADATA 4GB Notebook DDR3 1333MHz CL9 AD3S1333W4G9-R', stock:'3', description:'Memória mérete: 4GB Memória típusa: Notebook DDR3(SO-DIMM) Frekvencia : 1333 MHz Késleltetés : CL9',wholesale_price:'4817',vendor_id: '5');
Product.create!(image_url: Settings::ROOT + 'products/10100.jpg', category_id: 29, price:'22087', discount:'0', name: 'ADATA 8GB Notebook DDR3 1333MHz CL9 AD3S1333W8G9-R', stock:'5', description:'Memória mérete: 8GB Memória típusa: Notebook DDR3(SO-DIMM) Frekvencia : 1333 MHz Késleltetés : CL9',wholesale_price:'15461',vendor_id: '5');

Product.create!(image_url: Settings::ROOT + 'products/10101.jpg', category_id: 30,price:'11104',discount:'0',name:'GIGABYTE GV-R545-1GI HD5450 1GB GDDR3 PCIE',stock:'20',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn HD5450 Memória mérete: 1GB Memória típusa: DDR3 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem ',wholesale_price:'7772',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10102.jpg', category_id: 30,price:'14318',discount:'0',name:'SAPPHIRE 11190-09-20G HD6450 2GB DDR3 PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn HD6450 Memória mérete: 2GB Memória típusa: DDR3 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'10000',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10103.jpg', category_id: 30,price:'20345',discount:'0',name:'SAPPHIRE 11216-01-20 R7 240 1GB GDDR5 Boost PCIE',stock:'20',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn R7 240 Memória mérete: 1GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'14241',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10104.jpg', category_id: 30,price:'23727',discount:'0',name:'SAPPHIRE 11215-19-10G R7 250 1GB GDDR5 PCIE OEM',stock:'20',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn R7 250 Memória mérete: 1GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'16608',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10105.jpg', category_id: 30,price:'32502 ',discount:'0',name:'XFX R7-360P-2SF5 R7 360 2GB GDDR5 Core Edition PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn R7 360 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'22751',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10106.jpg', category_id: 30,price:'37776',discount:'0',name:'ASUS R7360-2GD5 R7 360 2GB GDDR5 PCIE',stock:'8',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn R7 360 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'26440',vendor_id:'2');
Product.create!(image_url: Settings::ROOT + 'products/10107.jpg', category_id: 30,price:'50494',discount:'0',name:'ASUS R7265-DC2-2GD5 R7 265 2GB GDDR5 PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: AMD Videó chipset: RadeOn R7 265 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'35345',vendor_id:'2');

Product.create!(image_url: Settings::ROOT + 'products/10108.jpg', category_id:31,price:'11104',discount:'0',name:'GIGABYTE GV-N710D3-1GL GT710 1GB DDR3 PCIE',stock:'5',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GT for Multi-media Videó chipset: GeForce GT710 A beszerelt memória mennyisége Memória mérete: 1GB Memória típusa: DDR3 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'7764',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10109.jpg', category_id:31,price:'13847',discount:'0',name:'GAINWARD 2630-BLISS GT610 2GB DDR3 PCIE',stock:'11',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GT for Multi-media Videó chipset: GeForce GT610 Memória mérete: 2GB Memória típusa: DDR3 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'9692',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10110.jpg', category_id:31,price:'20803',discount:'0',name:'ASUS GT730-2GD5-BRK GT730 2GB GDDR5 PCIE',stock:'3',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GT for Multi-media Videó chipset: GeForce GT730 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem ',wholesale_price:'14562',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10111.jpg', category_id:31,price:'24882',discount:'0',name:'ZOTAC ZT-71115-20L GT730 4GB DDR3 Zone PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GT for Multi-media Videó chipset: GeForce GT730 Memória mérete: 4GB Memória típusa: DDR3 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'17414',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10112.jpg', category_id:31,price:'31288',discount:'0',name:'GAINWARD 3545-BLISS GTX750 1GB GDDR5 Golden Sample PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GTX for Gaming Videó chipset: GeForce GTX750 Memória mérete: 1GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'20901',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10113.jpg', category_id:31,price:'34131',discount:'0',name:'EVGA 02G-P4-3747-KR GT740 2GB GDDR5 SC PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GT for Multi-media Videó chipset: GeForce GT740 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Nem DisplayPort : Nem Mini DisplayPort : Nem Mini HDMI : Igen Micro HDMI : Nem',wholesale_price:'23893',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10114.jpg', category_id:31,price:'48785',discount:'0',name:'MSI GTX 950 2GD5 OC GTX950 2GB GDDR5 OC PCIE',stock:'7',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GTX for Gaming Videó chipset: GeForce GTX950 Memória mérete: 2GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'34149',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10115.jpg', category_id:31,price:'58409',discount:'0',name:'GIGABYTE GV-N960OC-4GD GTX960 4GB GDDR5 OC PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GTX for Gaming Videó chipset: GeForce GTX960 Memória mérete: 4GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'40886',vendor_id:'10');
Product.create!(image_url: Settings::ROOT + 'products/10116.jpg', category_id:31,price:'95827',discount:'0',name:'GIGABYTE GV-N970IX-4GD GTX970 4GB GDDR5 PCIE',stock:'10',description:'VGA csatoló: PCI-E Chipset gyártó: NVIDIA Geforce GT/GTX : GeForce GTX for Gaming Videó chipset: GeForce GTX970 Memória mérete: 4GB Memória típusa: GDDR5 DVI: Igen HDMI: Igen DisplayPort : Igen Mini DisplayPort : Nem Mini HDMI : Nem Micro HDMI : Nem',wholesale_price:'67078',vendor_id:'10');

Product.create!(image_url: Settings::ROOT + 'products/10117.jpg', category_id:32,price:'1746',discount:'0',name:'4WORLD AS-1',stock:'6',description:'Nyelv: Angol Szín : Fekete USB csatlakozó: Igen',wholesale_price:'1222',vendor_id:'13');
Product.create!(image_url: Settings::ROOT + 'products/10118.jpg', category_id:32,price:'1881',discount:'0',name:'GENIUS KB-06XE PS/2',stock:'8',description:'Nyelv: Magyar Szín : Fekete PS/2 csatlakozó: Igen',wholesale_price:'1317',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10119.jpg', category_id:32,price:'2642',discount:'0',name:'GENIUS KB-M205 piros USB',stock:'11',description:'Nyelv: Magyar Szín : Fekete-Piros Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'1850',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10120.jpg', category_id:32,price:'3061',discount:'0',name:'GENIUS LuxeMate i200',stock:'9',description:'Nyelv: Magyar Szín : Fekete USB csatlakozó: Igen',wholesale_price:'2143',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10121.jpg', category_id:32,price:'3442',discount:'0',name:'GENIUS KB-G235',stock:'7',description:'Nyelv: Magyar Szín : Fekete Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'2410',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10122.jpg', category_id:32,price:'4750',discount:'0',name:'GENIUS Scorpion K215 Gaming',stock:'5',description:'Nyelv: Magyar Szín : Fekete Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'3325',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10123.jpg', category_id:32,price:'10414',discount:'0',name:'GENIUS Imperator',stock:'6',description:'Nyelv: Angol Szín : Fekete Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'7290',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10124.jpg', category_id:32,price:'17969',discount:'0',name:'GENIUS Manticore',stock:'3',description:'Nyelv: Angol Szín : Fekete Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'12578',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10125.jpg', category_id:32,price:'3556',discount:'0',name:'MICROSOFT Wired Keyboard 200 USB',stock:'7',description:'Nyelv: Magyar Szín : Fekete USB csatlakozó: Igen',wholesale_price:'2489',vendor_id:'12');
Product.create!(image_url: Settings::ROOT + 'products/10126.jpg', category_id:32,price:'6165',discount:'0',name:'MICROSOFT Comfort Curve 3000',stock:'5',description:'Nyelv: Magyar Szín : Fekete USB csatlakozó: Igen',wholesale_price:'4316',vendor_id:'12');
Product.create!(image_url: Settings::ROOT + 'products/10127.jpg', category_id:32,price:'14709',discount:'0',name:'MICROSOFT Natural Ergomonic Keyboard 4000',stock:'2',description:'Nyelv: Angol Szín : Fekete Multimédia : Igen USB csatlakozó: Igen',wholesale_price:'10296',vendor_id:'12');

Product.create!(image_url: Settings::ROOT + 'products/10128.jpg', category_id:33,price:'9176',discount:'0',name:'GEMBIRD KB-BT-02 fekete',stock:'14',description:'Nyelv: Angol Szín : Fekete Multimédia : Igen Vezeték nélküli : Igen',wholesale_price:'10296',vendor_id:'14');
Product.create!(image_url: Settings::ROOT + 'products/10129.jpg', category_id:33,price:'10466',discount:'0',name:'GEMBIRD Phoenix KB-P8-W',stock:'9',description:'Nyelv: Angol Szín : Feher Vezeték nélküli : Igen',wholesale_price:'7326',vendor_id:'14');
Product.create!(image_url: Settings::ROOT + 'products/10130.jpg', category_id:33,price:'11255',discount:'0',name:'MICROSOFT All-in-One Media Keyboard',stock:'6',description:'Nyelv: Magyar Szín : Fekete Multimédia : Igen Vezeték nélküli : Igen',wholesale_price:'7879',vendor_id:'12');
Product.create!(image_url: Settings::ROOT + 'products/10131.jpg', category_id:33,price:'13119',discount:'0',name:'MICROSOFT Arc',stock:'4',description:'Nyelv: Angol Szín : Fekete Vezeték nélküli : Igen',wholesale_price:'9183',vendor_id:'12');
Product.create!(image_url: Settings::ROOT + 'products/10132.jpg', category_id:33,price:'17752',discount:'0',name:'GIGABYTE FORCE K7 Wireless',stock:'2',description:'Nyelv: Angol Szín : Fekete Multimédia : Igen Vezeték nélküli : Igen',wholesale_price:'12426',vendor_id:'16');

Product.create!(image_url: Settings::ROOT + 'products/10133.jpg', category_id: 34, price:'1346', discount:'0', name:'CANYON CNE-CMS1', stock:'10', description:'Érzékelo: Optikai Gombok száma : 3 db Bluetooth: Nem Vezeték nélküli : Nem USB csatlakozó: Igen PS/2 csatlakozó: Nem',wholesale_price:'942',vendor_id: '18');
Product.create!(image_url: Settings::ROOT + 'products/10134.jpg', category_id: 34, price:'1657', discount:'0', name:'GEMBIRD MUS-U-002 fekete-ezüst', stock:'3', description:'Érzékelo: Optikai Gombok száma : 3 db Bluetooth: Nem Vezeték nélküli : Nem USB csatlakozó: Igen PS/2 csatlakozó: Nem',wholesale_price:'1159',vendor_id: '14');
Product.create!(image_url: Settings::ROOT + 'products/10135.jpg', category_id: 34, price:'1892', discount:'0', name:'GENIUS DX-150 Fekete', stock:'10', description:'Érzékelo: Optikai Gombok száma : 3 db Bluetooth: Nem Vezeték nélküli : Nem USB csatlakozó: Igen PS/2 csatlakozó: Nem',wholesale_price:'1324',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10136.jpg', category_id: 34, price:'2248', discount:'0', name:'ASUS UT210 Fehér-fekete', stock:'10', description:'Érzékelo: Optikai Gombok száma : 3 db Bluetooth: Nem Vezeték nélküli : Nem USB csatlakozó: Igen PS/2 csatlakozó: Nem',wholesale_price:'1574',vendor_id: '3');
Product.create!(image_url: Settings::ROOT + 'products/10137.jpg', category_id: 34, price:'2438', discount:'0', name:'GENIUS X-G200 fekete', stock:'10', description:'1000 DPI-s,USB-s 3 gombos optikai egér.',wholesale_price:'1706',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10138.jpg', category_id: 34, price:'2938', discount:'0', name:'ASUS UT210 Fekete', stock:'10', description:'Precíziós, 1000 DPI-s optikai vezérlés ergonomikus, gyors görgetokerékkel',wholesale_price:'2056',vendor_id: '3');
Product.create!(image_url: Settings::ROOT + 'products/10139.jpg', category_id: 34, price:'9438', discount:'0', name:'ASUS ROG Sica', stock:'10', description:'5000 DPI-s optikai egér USB csatlakozással játékosoknak.',wholesale_price:'6640',vendor_id: '3');
Product.create!(image_url: Settings::ROOT + 'products/10140.jpg', category_id: 34, price:'10668', discount:'0', name:'GENIUS DeathTaker', stock:'10', description:'9 gombos, USB-s, súlyozható optikai gamer egér.',wholesale_price:'7467',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10141.jpg', category_id: 34, price:'13994', discount:'0', name:'ASUS Echelon laser gaming mouse', stock:'10', description:'- Tökéletes precizitás - 5 módban állítható érzékenység - Automatikus kattintás ismétlo funkció - 8 programozható gomb - Testre szabható súlyozás',wholesale_price:'9795',vendor_id: '3');
Product.create!(image_url: Settings::ROOT + 'products/10142.jpg', category_id: 34, price:'15118', discount:'0', name:'RAZER Abyssus - Ambidextrous', stock:'10', description:'Jól tapintható ergonomikus gombok, 3500dpi optikai érzékelo,Zöld led,korlátlan profilok,eszközök közöttki kommunikáció.',wholesale_price:'10582',vendor_id: '15');

Product.create!(image_url: Settings::ROOT + 'products/10143.jpg', category_id: 35, price:'2075', discount:'0', name:'GEMBIRD MUSW-101 fekete', stock:'10', description:'Fekete vezeték nélküli optikai egér.',wholesale_price:'1452',vendor_id: '14');
Product.create!(image_url: Settings::ROOT + 'products/10144.jpg', category_id: 35, price:'2442', discount:'0', name:'GENIUS NX-7015 fekete-szürke', stock:'13', description:'1600 DPI-s BluEye szenzoros vezeték nélküli egér.',wholesale_price:'1710',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10145.jpg', category_id: 35, price:'3232', discount:'0', name:'GENIUS NS-6000 fekete', stock:'10', description:'3 gombos fekete színu vezeték nélküli egér.',wholesale_price:'2262',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10146.jpg', category_id: 35, price:'3556', discount:'0', name:'GENIUS NS-6015 fekete - kék', stock:'10', description:'Vezeték nélküli optikai egér.',wholesale_price:'2489',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10147.jpg', category_id: 35, price:'3932', discount:'0', name:'GIGABYTE GM-M7580', stock:'10', description:'3 gombos fekete optikai egér, 500 - 1000 dpi.',wholesale_price:'2752',vendor_id: '16');
Product.create!(image_url: Settings::ROOT + 'products/10148.jpg', category_id: 35, price:'5601', discount:'0', name:'GENIUS Traveler 9020BT szürke-fekete', stock:'10', description:'- Bluetooth 4 gombos vezeték nélküli optikai egér - Könnyen válthat Bluetooth-os PC / NB / Tablet PC között - Kényelmes, kétkezes fogás - Eroteljes BlueEye technológia (minden felületen muködik) - Kompatibilis a három operációs rendszerek - Kényelmes elemtartó design',wholesale_price:'3920',vendor_id: '11');
Product.create!(image_url: Settings::ROOT + 'products/10149.jpg', category_id: 35, price:'6280', discount:'0', name:'GIGABYTE Aire M73 fekete', stock:'10', description:'Gigabyte Aire M73 vezeték nélküli optikai egér. - felbontás: 1000 dpi - méret: 123 x 76 x 43 mm - súly: 91 g',wholesale_price:'4396',vendor_id: '16');
Product.create!(image_url: Settings::ROOT + 'products/10150.jpg', category_id: 35, price:'7209', discount:'0', name:'HP X4000b Bluetooth egér H3T50AA', stock:'10', description:'Érzékelo: Lézer Gombok száma : 3 db Bluetooth: Igen Vezeték nélküli : Igen USB csatlakozó: Igen',wholesale_price:'5046',vendor_id: '20');
Product.create!(image_url: Settings::ROOT + 'products/10151.jpg', category_id: 35, price:'8533', discount:'0', name:'MICROSOFT Sculpt Mobile Mouse fekete', stock:'10', description:'Vezeték nélküli optikai egér fekete színben.',wholesale_price:'5973',vendor_id: '12');
Product.create!(image_url: Settings::ROOT + 'products/10152.jpg', category_id: 35, price:'11836', discount:'0', name:'HP Star Wars Special Edition Wireless Mouse P3E54AA', stock:'10', description:'1600 DPI-s csillagok háborúja mintás lézer szenzoros vezeték nélküli egér.',wholesale_price:'8285',vendor_id: '20');

Product.create!(image_url: Settings::ROOT + 'products/10153.jpg', category_id:9,price:'3096',discount:'0',name:'4WORLD 05547 Stereo Sound Wave',stock:'10',description:'Mágnesesen árnyékolt,Beépített erősítő,Frekvenciaátvitel: 60 Hz - 20 kHz,Impedancia: 50 Ohm,THD 0,05%,Bemeneti érzékenység: 200mV-1.2V,mini Jack dugó,Kompatibilis a PC és Macintosh számítógépekkel',wholesale_price:'2167',vendor_id:'13');
Product.create!(image_url: Settings::ROOT + 'products/10154.jpg', category_id:9,price:'3212',discount:'0',name:'4WORLD 05548 Stereo Power Sound',stock:'8',description:'Impedancia: 8 Ohm Zenei teljesítmény 0.5 W x 2 Basszus kamra s kiváló minőségű hangért,Hangerő szabályozó,Jack fejhallgató csatlakozó,Mágnesesen árnyékolt,Multimédia PC kompatibilis',wholesale_price:'2248',vendor_id:'13');
Product.create!(image_url: Settings::ROOT + 'products/10155.jpg', category_id:9,price:'2584',discount:'0',name:'GENIUS SP-U 115',stock:'14',description:'Hangrendszer: 2.0 Csatlakozás : USB és Jack Hangerő : 1 watt',wholesale_price:'1809',vendor_id:'16');
Product.create!(image_url: Settings::ROOT + 'products/10156.jpg', category_id:9,price:'2832',discount:'0',name:'GENIUS SP-S 110',stock:'10',description:'Hangrendszer: 2.0 Csatlakozás : Jack Hangerő : 1 watt',wholesale_price:'1982',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10157.jpg', category_id:9,price:'3734',discount:'0',name:'GENIUS SP-M 150',stock:'7',description:'Hangrendszer: 2.0 Csatlakozás : Jack Hangerő : 4 watt',wholesale_price:'2614',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10158.jpg', category_id:9,price:'6121',discount:'0',name:'GENIUS SW-S 2.1 200',stock:'11',description:'Hangrendszer: 2.1 Csatlakozás : Jack Hangerő : 5 watt',wholesale_price:'4285',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10159.jpg', category_id:9,price:'7320',discount:'0',name:'GENIUS SW-2.1 375 fa',stock:'6',description:'Hangrendszer: 2.1 Csatlakozás : Jack Hangerő : 12 watt',wholesale_price:'5124',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10160.jpg', category_id:9,price:'11460',discount:'0',name:'GENIUS SP-HF 800A',stock: '4',description:'Hangrendszer: 2.0 Csatlakozás : Jack Hangerő : 20 watt',wholesale_price:'8022',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10161.jpg', category_id:9,price:'26533',discount:'0',name:'GENIUS SP-HF 800A',stock:'4',description:'Hangrendszer: 5.1 Csatlakozás : Jack Hangerő : 80 watt',wholesale_price:'18573',vendor_id:'11');
Product.create!(image_url: Settings::ROOT + 'products/10162.jpg', category_id:9,price:'40833',discount:'0',name:'RAZER Leviathan Mini',stock:'3',description:'Hangrendszer: 2.0 Csatlakozás : Bluetooth Hangerő : 24 watt',wholesale_price:'28583',vendor_id:'15');